name: Update Announcements

on:
  schedule:
    # 15分ごとに実行
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python ./.github/workflows/update_script.py
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          # GH_PATはもう不要
          # GITHUB_USERとGITHUB_REPOも不要

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # 両方のファイルをaddする
          git add announcements.json .github/workflows/last_message_id.txt
          # ファイルに変更があった場合のみコミット
          if ! git diff --staged --quiet; then
            git commit -m "[Bot] Update announcements"
            git push
          else
            echo "No changes to commit."
          fi
